version: "3"

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    networks:
      - db

networks:
  db:
    external: true
