version: "3.5"

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    networks:
      - db

networks:
  db:
    external: true
