version: "3.5"

services:
  loadbalancer:
    image: traefik:v2.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpChallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=info@splintnet.de"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.headers.sslRedirect=true"

      # - "traefik.http.routers.api.rule=Host(`docker.5-anker.com`)"
      ## - "traefik.http.routers.api.entrypoints=websecure"
      # - "traefik.http.routers.api.service=api@internal"
      # - "traefik.http.routers.api.middlewares=traefikauth"
      # - "traefik.http.routers.api.tls.certresolver=myhttpchallenge"
      # - "traefik.http.routers.api.tls=true"
      # - "traefik.http.middlewares.traefikauth.basicauth.users=docker:{SHA}AazQ8lOcLWZ7vO3N/KkzXVRuiws="
      # - "traefik.http.middlewares.traefikauth.basicauth.removeheader=true"

      ## - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      ## - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      ## - "traefik.http.routers.http-catchall.priority=1"

networks:
  traefik:
    external: true
