version: "3.5"

services:
  loadbalancer:
    image: traefik:v2.4
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      # - "--api.insecure=true"
      # - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      # - "--providers.file.filename=/dyn.yaml"
      # - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpChallenge=true"
      - "--certificatesresolvers.le.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.le.acme.email=info@splintnet.de"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      # - ./certificates:/certificates
      # - ./dyn.yaml:/dyn.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
